JUMBO:
  DATE:
    (?<!//)(?P<capture>(?:\d{2}\/){2}\d{4})(?!\\nVIGENCIA)
  STORE_ADDRESS:
    AGENTE RETENEDOR DE IVA.+?\n(?P<capture>.+?)(?=VENDEDOR ELECTRO|TEL\:)
  INVOICE_NUMBER:
    TIQUETE\s(?P<capture>[\w\s]+)\n
  NUMBER_OF_ITEMS:
    ITEMS\sCOMPRADOS\:\s(?P<capture>\d+)
  SUBTOTAL:
    (?P<capture>empty value)
  TOTAL:
    \nTOTAL\n(?P<capture>\d+)
  SKU:
    (\d{13})\s.{1,16}?\n
  DESCRIPTION:
    \d{13}\s(.{1,16}?)\n
  TOTAL_PER_ITEM:
    (empty value)
  TAX_CODE:
    (?<=\n)\d+\s?([ANF]|\n)(?=\d|\n|SUBTOTAL)